language: java

addons:
  apt:
    update: true
  chrome: stable
  firefox: stable

jobs:
  include:
    - script: mvn clean test -P chrome
      name: "Maven Chrome"
    - script: mvn clean test -P firefox
      name: "Maven Firefox"
#    - script: ./gradlew chrome --no-daemon --console=plain -i
#      name: "Gradle Chrome"
#    - script: ./gradlew firefox --no-daemon --console=plain -i
#      name: "Gradle Firefox"
