version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
#      mvn clean test -P chrome

machine:
  java:
    version: 11

general:
  branches:
    only:
      - master # list of branches to build
